[server]
host = "0.0.0.0"
port = "7878"
threads = 4

[[resources]]
request = "/"
response = "/home/MattWaX/exercise-code/rust/rswebserver/www/index.html"

[[resources]]
request = "/style.css"
response = "/home/MattWaX/exercise-code/rust/rswebserver/www/style.css"
