[server]
host = "0.0.0.0"
port = "7878"
threads = 4

[[resources]]
request = "/"
response = "/home/MattWaX/exercise-code/rust/rswebserver/www/index.html"

# [[resources]]
# request = "/web"
# response = "/home/MattWaX/Projects/comino18.mattwax.xyz/www/index.html"
